// Generated by CoffeeScript 1.11.1
(function() {
  var arr, client, connectionOpened, context, decodeError, nextStartTime, numSegments, playAudio, streamData, streamDone, streamStarted;

  client = new BinaryClient('ws://localhost:9696');

  context = new AudioContext();

  arr = [];

  nextStartTime = 0;

  numSegments = 0;

  connectionOpened = function() {
    return console.log("Established connection to server");
  };

  streamStarted = function(stream, meta) {
    stream.on('data', streamData);
    stream.on('end', streamDone);
    return console.log("Stream of frames started");
  };

  streamData = function(data) {
    return context.decodeAudioData(data, playAudio, decodeError);
  };

  decodeError = function() {
    return console.log("Decoding failed");
  };

  streamDone = function() {
    return console.log("Received all MP3 fragments from server");
  };

  playAudio = function(buffer) {
    var source;
    //source = context.createBufferSource();
    //source.buffer = buffer;
    //source.connect(context.destination);
    //source.start(nextStartTime);
    console.log(nextStartTime);
    if (nextStartTime === 0) {
      return nextStartTime = context.currentTime;
    } else {
      return nextStartTime = nextStartTime + buffer.duration;
    }
  };

  client.on('open', connectionOpened);

  client.on('stream', streamStarted);

}).call(this);
